# build init from alpine base
ARG ALPINE_VERSION=3.12
ARG ALPINE_DOCKER_VERSION=3.10
FROM alpine:${ALPINE_DOCKER_VERSION} as initbasestage
ARG ALPINE_VERSION

RUN \
 echo "**** install build deps ****" && \
 apk add --no-cache --upgrade \
	curl \
	tar \
	xz 

RUN \
 echo "**** install yq form edge/testing/community repository ****" && \
 apk add --no-cache --upgrade --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community \
	yq

RUN \
 echo "**** grab Alpine ****" && \
 mkdir -p /initrd && \
 LATEST=$(curl -sL \
	http://dl-cdn.alpinelinux.org/alpine/v${ALPINE_VERSION}/releases/x86_64/latest-releases.yaml \
	| yq read - [0].version) && \
 echo $LATEST && \
 curl -o \
        /rootfs.tar.gz -L \
        "http://dl-cdn.alpinelinux.org/alpine/v${ALPINE_VERSION}/releases/x86_64/alpine-minirootfs-${LATEST}-x86_64.tar.gz" && \
 tar xf \
	/rootfs.tar.gz \
	-C /initrd

RUN \
 echo "**** grab Alpine linux-lts version ****" && \
 LATESTbranch=$(curl -sL \
	http://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/x86_64/latest-releases.yaml \
	| yq read - [0].branch) && \
 echo LATESTbranch: $LATESTbranch && \
  linuxVERSION=$(pkgNAME="linux-lts" ; apk info --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/v${ALPINE_VERSION}/main ${pkgNAME} \
                | grep "description:" | cut -d" " -f1 | sed -e "s/${pkgNAME}//" | cut -d"-" -f2 ) && \
 echo linuxVERSION: "$linuxVERSION"

# build kernel
FROM alpine:${ALPINE_DOCKER_VERSION} as buildstage
#ARG KERNEL_VERSION="5.4.58"
RUN  linuxVERSION=$(pkgNAME="linux-lts" ; apk info --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/v${ALPINE_VERSION}/main ${pkgNAME} \
                | grep "description:" | cut -d" " -f1 | sed -e "s/${pkgNAME}//" | cut -d"-" -f2 ) && \
     echo linuxVERSION: "$linuxVERSION"

RUN \
 echo "**** download assets ${KERNEL_VERSION} ${linuxVERSION} $KERNEL_VERSION $linuxVERSION ****" && \
 wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-${KERNEL_VERSION}.tar.xz && \
 wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-${KERNEL_VERSION}.tar.sign && \
 xz -v -d linux-${KERNEL_VERSION}.tar.xz && \
 gpg --keyserver keyserver.ubuntu.com --recv B8868C80BA62A1FFFAF5FDA9632D3A06589DA6B1 647F28654894E3BD457199BE38DBBDC86092693E ABAF11C65A2970B130ABE3C479BE3E4300411886 && \
 gpg --verify linux-${KERNEL_VERSION}.tar.sign && \
 tar xf linux-${KERNEL_VERSION}.tar 
 
