name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: /bin/bash -e build.sh

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        #path: path/**/[abc]rtifac?/*
        path: vmlinuz*
